config/routes.rb
Bioinformatica::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :info_snippets do
    resources :tags, :only => [:index]
  end

  resources :tags do
    resources :info_snippets, :only => [:index]
    resources :programs, :only => [:index]
  end

  resources :tag_types, :only => [:show] do
    resources :tags, :only => [:index]
  end

  resources :programs do
    resources :tags, :only => [:index]
  end

  resources :companies

  root :to => 'bioinformatica#index'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_and_belongs_to_many :programs
  has_and_belongs_to_many :info_snippets

  validate :has_name_or_ticker

  scope :by_name, order('name ASC')

  validates_numericality_of :'52_week_high', allow_nil: true, greater_than: :'52_week_low', :if => Proc.new {|company| company['52_week_high'].present? && company['52_week_low'].present? }, message: 'cannot be less than 52 week low'
  validates_numericality_of :price, allow_nil: true
  validates_numericality_of :cash, allow_nil: true
  validates_numericality_of :shares_out, allow_nil: true
  validates_numericality_of :burn, allow_nil: true
  validates_numericality_of :three_month_volume, allow_nil: true
  validates_numericality_of :debt, allow_nil: true

  attr_accessible :name, :ticker, :price, :'52_week_high', :'52_week_low', :cash,
                  :shares_out, :burn, :three_month_volume, :debt, :debt_due,
                  :info_snippet_ids, :program_ids, :three_month_volume, :other
end

def has_name_or_ticker
  if [self.name, self.ticker].reject(&:blank?).size == 0
    errors[:base] << ("Company requires either a name or a ticker")
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  respond_to :json

  def index
    companies = Company.by_name
    @company_hash = companies.map do |c|
      {
        id: c.id,
        name: c.name,
        ticker: c.ticker
      }
    end
    render_json
  end

  def show
    company = Company.find_by_id(params[:id])
    if company.present?
      @financials =
        {
          price: company.price,
          f52high: company[:'52_week_high'],
          f52low: company[:'52_week_low'],
          cash: company.cash,
          shares_out: company.shares_out,
          three_month_volume: company.three_month_volume,
          burn: company.burn,
          debt: company.debt,
          debt_due: company.debt_due
        }

      add_calculated_financial(:market_cap, company.price, company.shares_out, "*")
      add_calculated_financial(:three_month_dollar_volume, company.price, company.three_month_volume, "*")
      add_calculated_financial(:runway, company.cash, company.burn, '/')

      programs = company.programs.map do |p|
        {
          id: p.id,
          name: p.name,
          description: p.description,
          tags: p.tags
        }
      end

      snippets = company.info_snippets.by_date_r
      timeline_snippets = snippets.select {|s| s.timeline_snippet}
      diligence_snippets = snippets - timeline_snippets

      @company_hash =
        [{
          id: company.id,
          name: company.name,
          ticker: company.ticker,
          programs: programs,
          financials: @financials,
          timeline_snippets: timeline_snippets,
          diligence_snippets: diligence_snippets,
          other: company.other
          }]
      render_json
    end
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    company_id = params.require(:id)
    @company = Company.find(company_id)

    if @company.update_attributes(company_params)
      redirect_to "/#/company=#{company_id}"
    else
      render :edit
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
  end

  private

  def add_commas_to_large_numbers_in_financials
    @financials.each {|k,v| @financials[k] = add_commas_to_large_number(v) }
  end

  def add_calculated_financial(symbol, first_item, second_item, operation)
    return nil unless first_item.present? && second_item.present? && operation.present?

    case operation
    when "*"
      @financials = @financials.merge({ symbol => first_item * second_item})
    when "/"
      return nil if second_item < 1
      @financials = @financials.merge({ symbol => first_item / second_item})
    else
      nil
    end
  end

  def company_params
    company_info = params.require(:company)
    company_info.permit(
      :name,
      :ticker,
      :price,
      :'52_week_high',
      :'52_week_low',
      :cash,
      :shares_out,
      :three_month_volume,
      :debt,
      :debt_due,
      :burn,
      :other
    )
  end

  def render_json
    render :json => @company_hash
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form_content.html.haml
.error-explanation
  - if @company.errors.any?
    %h5= 'Please fix the following errors:'
    %ul
      - @company.errors.full_messages.each do |msg|
        %li= msg
.input-content
  %ul.no-style
    %li
      = 'Name:'
      .input-field= c.text_field :name
    %li
      = 'Ticker:'
      .input-field= c.text_field :ticker
    %li
      = 'Price:'
      .input-field= c.text_field :price
    %li
      = '52-week High:'
      .input-field= c.text_field :'52_week_high'
    %li
      = '52-week Low:'
      .input-field= c.text_field :'52_week_low'
    %li
      = 'Shares Out (in millions):'
      .input-field= c.text_field :shares_out
    %li
      = 'Cash (in millions):'
      .input-field= c.text_field :cash
    %li
      = 'Debt (in millions):'
      .input-field= c.text_field :debt
    %li
      = 'Debt Due:'
      .input-field= c.date_select :debt_due, :include_blank => true
    %li
      = 'Burn:'
      .input-field= c.text_field :burn
    %li
      = '3 Month Average Daily Volume:'
      .input-field= c.text_field :three_month_volume
    %li
      = 'Other Details and Notes'
      .input-field= c.text_area :other

.create-button
  = c.submit

app/views/companies/edit.html.haml
= render :partial => './haml_nav'

.container#edit-company-container
  %h3= 'Edit Company'

  .company-form
    = form_for @company, url: company_path(@company) do |c|
      = render partial: 'form_content', locals: {c: c}

app/views/companies/new.html.haml
= render :partial => './haml_nav'

.container#edit-company-container
  %h3= 'New Company'

  .company-form
    = form_for @company, url: companies_path do |c|
      = render partial: 'form_content', locals: {c: c}