config/routes.rb
Bioinformatica::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :info_snippets do
    resources :tags, :only => [:index]
  end

  resources :tags do
    resources :info_snippets, :only => [:index]
    resources :programs, :only => [:index]
  end

  resources :tag_types, :only => [:show] do
    resources :tags, :only => [:index]
  end

  resources :programs do
    resources :tags, :only => [:index]
  end

  resources :companies

  root :to => 'bioinformatica#index'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :tag_type
  has_and_belongs_to_many :info_snippets
  has_and_belongs_to_many :programs

  has_many :companies, through: :programs

  scope :by_name, order('name ASC')
  scope :by_name_desc, order('name DESC')

  validates :name, presence: true
  validates :tag_type, presence: true
  validates_associated :tag_type
  validates_associated :info_snippets
  validates_associated :programs

  attr_accessible :name, :tag_type_id, :info_snippet_ids, :program_ids

  def self.find_or_create_new(name, type)
    tag_type = TagType.find_by_name(type) #TODO: blow up if type not found
    tag = Tag.find_by_name_and_type(name, tag_type) || Tag.create(name: name, tag_type_id: tag_type.id)
  end

  def self.find_by_name_and_type(name, tag_type)
    tag_type.tags.each do |tag|
      return tag if equivalent_names(tag.name, name)
    end
    nil
  end

  private

  #TODO: add similar tag name checks in the future
  def self.equivalent_names(tag_name, name)
    tag_name.downcase == name.downcase
  end
end

app/models/tag_type.rb
class TagType < ActiveRecord::Base
  attr_accessible :name

  scope :by_name, order('name ASC')

  validates :name, presence: true

  has_many :tags
end

app/models/tags.rb
class Tags < ActiveRecord::Base
  belongs_to :tag_type
  has_many :info_snippets

  validates :tag, presence: true
  validates :tag_type, presence: true
  validates_associated :tag_type
  validates_associated :info_snippets

  attr_accessible :tag, :tag_type_id
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  respond_to :json

  def index
    tags =  if params["info_snippet_id"].present?
              InfoSnippet.find_by_id(params["info_snippet_id"]).tags
            elsif params["program_id"].present?
              Program.find_by_id(params["program_id"]).tags
            else
              Tag.all
            end
    @tag_hash = {}

    TagType.all.each do |type|
      type_array = []
      @tag_hash[type.name] = type.tags & tags
      @tag_hash[type.name].collect! do |tag|
        {
          id: tag.id,
          name: tag.name,
          type: tag.tag_type.name,
          type_id: tag.tag_type.id
        }
      end
    end

    render_json
  end

  def show
    tag = Tag.find_by_id(params[:id])

    companies = tag.companies.map do |company|
      {
        id: company.id,
        ticker: company.ticker
      }
    end

    @tag_hash =
      [{
        id: tag.id,
        name: tag.name,
        type: tag.tag_type.name,
        type_id: tag.tag_type.id,
        companies: companies.uniq
      }]
    render_json
  end

  def new
    @tag = Tag.new
    @tag_types = TagType.by_name
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to '/#/snippet'
    else
      @tag_types = TagType.by_name
      render :new
    end
  end

  def edit
    @tag = Tag.find(params[:id])
    @tag_types = TagType.by_name
    @current_type_id = @tag.tag_type_id
  end

  def update
    tag_id = params.require(:id)
    @tag = Tag.find(tag_id)

    if @tag.update_attributes(tag_params)
      redirect_to "/#/tag=#{tag_id}"
    else
      @tag_types = TagType.by_name
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
  end

  private

  def tag_params
    tag_info = params.require(:tag)
    tag_type = tag_info.require(:tag_type_id)

    tag_info.permit(
      :id,
      :name,
      :tag_type_id
    )
  end

  def render_json
    render :json => @tag_hash
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/edit.html.haml
= render :partial => './haml_nav'

.container#edit-tag-container
  %h3= 'New Tag'

  .drug-form
    = form_for @tag, url: tag_path(@tag) do |t|
      .error-explanation
        - if @tag.errors.any?
          %h5= 'Please fix the following errors:'
          %ul
            - @tag.errors.full_messages.each do |msg|
              %li= msg
      .input-content
        %ul.no-style
          %li
            = 'Tag Type'
            .input-field= t.select :tag_type_id, options_from_collection_for_select(@tag_types, 'id', 'name', @current_type_id)
          %li
            = 'Name:'
            .input-field= t.text_field :name
      .create-button
        = t.submit

app/views/tags/new.html.haml
= render :partial => './haml_nav'

.container#edit-tag-container
  %h3= 'New Tag'

  .drug-form
    = form_for @tag, url: tags_path do |t|
      .error-explanation
        - if @tag.errors.any?
          %h5= 'Please fix the following errors:'
          %ul
            - @tag.errors.full_messages.each do |msg|
              %li= msg
      .input-content
        %ul.no-style
          %li
            = 'Tag Type'
            .input-field= t.select :tag_type_id, options_from_collection_for_select(@tag_types, 'id', 'name')
          %li
            = 'Name:'
            .input-field= t.text_field :name
      .create-button
        = t.submit