config/routes.rb
Bioinformatica::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :info_snippets do
    resources :tags, :only => [:index]
  end

  resources :tags do
    resources :info_snippets, :only => [:index]
    resources :programs, :only => [:index]
  end

  resources :tag_types, :only => [:show] do
    resources :tags, :only => [:index]
  end

  resources :programs do
    resources :tags, :only => [:index]
  end

  resources :companies

  root :to => 'bioinformatica#index'
end

app/controllers/bioinformatica_controller.rb
class BioinformaticaController < ApplicationController
  respond_to :html

  def index
  end
end

app/helpers/bioinformatica_helper.rb
module BioinformaticaHelper
end

app/views/bioinformatica/_companies.html.haml
.container.span12{:'ng-controller' => 'company_controller'}
  .container#companies-list{:'ng-show' => '!one_company'}
    %h3= 'All Companies'
    %ul.no-style
      .li{:'ng-repeat' => 'c in companies'}
        %a{:'ng-click' => "select_company(c.id)"}
          .span{:'ng-show' => "c.ticker"} [ {{c.ticker}} ]
          {{c.name}}
  .container#company-description{:'ng-show' => 'one_company', :'class' => 'ng-cloak'}
    .ng-cloak
      %a{:'ng-click' => 'select_all()'}= '<-- Back to All Companies'
      %h1 {{one_company.name}} ({{one_company.ticker}})
      .span3
        .row#company-financials
          %h3= 'Financials'
          %ul.no-style
            %li
              Price:
              .financial ${{one_company.financials.price | number:2}}
            %li
              52-week high:
              .financial ${{one_company.financials.f52high | number:2}}
            %li
              52-week low:
              .financial ${{one_company.financials.f52low | number:2}}
            %li
              Cash (in millions):
              .financial ${{one_company.financials.cash | number}}
            %li
              Shares Out (in millions):
              .financial {{one_company.financials.shares_out | number:2}}
            %li
              Market Cap (in millions):
              .financial ${{one_company.financials.market_cap | number:2}}
            %li
              Cash (in millions):
              .financial ${{one_company.financials.cash | number}}
            %li
              Debt (in millions):
              .financial ${{one_company.financials.debt | number}}
            %li
              Debt Due:
              .financial {{one_company.financials.debt_due | date: 'MM/yyyy'}}
            %li
              Annualized Burn:
              .financial {{one_company.financials.burn | number}}
            %li
              Runway:
              .financial {{one_company.financials.runway | number}} Years
            %li
              3 Month Average Daily Volume:
              .financial {{one_company.financials.three_month_volume | number}}
            %li
              3 Month Average Daily $ Volume
              .measurement (in $ millions):
              .financial ${{one_company.financials.three_month_dollar_volume | number:2}}
        .row.edit-and-destroy
          %a.btn.edit{:'ng-click' => 'edit_company(one_company.id)', type: :submit, method: :get}= 'Edit Company'
          %a.btn.destroy{:'ng-click' => 'delete_company(one_company.id)', :'ng-confirm-click' => "Are you sure?"}= 'Delete Company'
      .span8#company-details
        .row#product-pipeline
          %h3= 'Drug Pipeline'
          %table
            %tr.program-description{:'ng-repeat' => 'p in one_company.programs'}
              %td.program-name
                %a{:'ng-click' => "select_program(p.id)"}= "{{p.name}}"
              %td
                {{p.description}}
                .program-tags
                  .tag{:'ng-repeat' => 't in p.tags'}
                    %a{:'ng-click' => "select_tag(t.id)"}= "{{t.name}}"
        .row.new-snippet-buton
          = button_to 'New Drug', new_program_path(company_id: "{{one_company.id}}"), method: :get

        .row#timeline
          %h3= 'Timeline'
          %table
            %tr.snippet{:'ng-repeat' => 's in one_company.timeline_snippets'}
              %td.date {{s.event_date | date: 'MM/yyyy'}}
              %td.catalyst
                %a{:'ng-click' => 'select_snippet(s.id)'} {{s.text}}
          .new-snippet-buton
            = button_to 'New Snippet', new_info_snippet_path, method: :get
        .row#diligence
          %h3= 'Diligence'
          %ul.no-style
            %li.info-snippet{:'ng-repeat' => 's in one_company.diligence_snippets'}
              %a.preserve-style{:'ng-click' => "select_snippet(s.id)"}
                .subject{:'ng-show' => 's.subject'} {{s.subject}}
                .scrollable.one-color {{s.text}}
              .event-date{:'ng-show' => 's.event_date'}= "Date: {{s.event_date | date: 'MM/dd/yyyy'}}"
          .new-snippet-buton
            = button_to 'New Snippet', new_info_snippet_path, method: :get
        .row#other
          %h3= 'Other Details and Notes'
          .preserve-style{:'ng-show' => 'one_company.other'} {{one_company.other}}

app/views/bioinformatica/_company.html.haml
.container.span12{id: 'company-container', 'ng-controller' => 'company_controller'}
  .row{id: 'financials'}
    %ul.no-style
      %li= "Price: {{company.price}}"
      %li= "52-week high: {{company.52high}}"
      %li= "52-week low: {{company.52low}}"
      %li= "Cash: {{company.cash}}"
      %li= "Market Cap: {{company.market_cap}}"
      %li= "Shares Out: {{company.shares}}"
      %li= "Burn: {{company.burn}}"
      %li= "Runway: {{company.runway}}"
  .row{id: 'Timeline'}
    %h3= 'Timeline'
    %ul.no-style
      %li
  .row{id: 'Diligence'}
  .row{id: 'SEC'}

app/views/bioinformatica/_nav.html.haml
#nav{:'ng-controller' => 'nav_controller'}
  %a#company-nav{:'ng-click' => 'show_all_companies()'}= 'All Companies'
  %a#program-nav{:'ng-click' => 'show_all_programs()'}= 'All Drugs'
  %a#conversation-nav{:'ng-click' => 'show_all_conversations_and_tags()'}= 'All Snippets'
  = link_to 'New Company', new_company_path
  = link_to 'New Drug', new_program_path
  = link_to 'New Tag', new_tag_path
  = link_to 'New Snippet', new_info_snippet_path

app/views/bioinformatica/_programs.html.haml
#programs-container{:'ng-controller' => 'programs_controller'}
  .row#programs-list{:'ng-show' => '!one_program'}
    %h3= 'Drugs'
    %ul.no-style
      %li.program{:'ng-repeat' => 'p in programs'}
        %a{:'ng-click' => "select_drug(p.id)"}= "{{p.name}}"
  .row#one-program{:'ng-show' => 'one_program'}
    .header
      %h3 {{one_program.name}}
      .preserve-style {{one_program.description}}
    .timeline-snippets
      %h3= 'Timeline'
      %table
        %tr.snippet{:'ng-repeat' => 's in one_program.timeline_snippets'}
          %td.date {{s.event_date}}
          %td.catalyst
            %a{:'ng-click' => 'select_snippet(s.id)'} {{s.text}}
    .diligence-snippets
      %h3= 'Diligence'
      %ul.no-style
        %li.info-snippet{:'ng-repeat' => 's in one_program.diligence_snippets'}
          %a.preserve-style{:'ng-click' => "select_snippet(s.id)"}
            .subject{:'ng-show' => 's.subject'} {{s.subject}}
            .scrollable.one-color {{s.text}}
          .event-date{:'ng-show' => 's.event_date'}= "Date: {{s.event_date | date: 'MM/dd/yyyy'}}"
    .companies
      %h3= 'Companies'
      %ul.no-style
        %li.company{:'ng-repeat' => 'c in one_program.companies'}
          %a{:'ng-click' => 'select_company(c.id)'}="{{c.name}}"

    .edit-and-destroy
      %a.btn.edit{:'ng-click' => 'edit_drug(one_program.id)'}= 'Edit Drug'
      %a.btn.destroy{:'ng-click' => 'delete_drug(one_program.id)', :'ng-confirm-click' => "Are you sure?"}= 'Delete Drug'

    .back
      %a{:'ng-click' => 'select_all()'}= '<-- Back to All Drugs'

app/views/bioinformatica/_snippets.html.haml
#snippets-container{:'ng-controller' => 'snippets_controller'}
  .row#snippet
    %h3= 'Snippets'
    %ul.no-style
      %li.info-snippet{:'ng-repeat' => 'i in info_snippets'}
        %a{:'ng-click' => "select_snippet(i.id)"}
          .subject{:'ng-show' => 'i.subject'}= "{{i.subject}}"
          .preserve-style.scrollable.one-color{:'ng-show' => '!showing_one_snippet'} {{i.text}}
          .preserve-style.one-color{:'ng-show' => 'showing_one_snippet'} {{i.text}}
          .event-date{:'ng-show' => 'i.event_date'}= "Date: {{i.event_date | date: 'MM/dd/yyyy'}}"
  .row#one-snippet-extras{:'ng-show' => 'showing_one_snippet'}
    .companies
      %h3= 'Companies'
      .company{:'ng-repeat' => 'company in info_snippets[0].companies'}
        %a{:'ng-click' => "select_company(company.id)"}= "{{company.ticker}}"
    .drugs
      %h3= 'Drugs'
      .drug{:'ng-repeat' => 'drug in info_snippets[0].drugs'}
        %a{:'ng-click' => "select_drug(drug.id)"}= "{{drug.name}}"
    .edit-and-destroy
      %a.btn.edit{:'ng-click' => 'edit_snippet(info_snippets[0].id)'}= 'Edit Snippet'
      %a.btn.destroy{:'ng-click' => 'delete_snippet(info_snippets[0].id)', :'ng-confirm-click' => "Are you sure?"}= 'Delete Snippet'

app/views/bioinformatica/_tags.html.haml
#tags-container{:'ng-controller' => 'tags_controller'}
  %h3= 'Tags'
  .tags-nav#tags-list{:'ng-show' => '!one_tag'}
    %ul.no-style
      %li{:'ng-repeat' => '(type, t) in tags'}
        .type{:'ng-hide' => "t.length == 0"}
          %h5 {{type}}
          %ul.no-style
            %li.tag{:'ng-repeat' => 'tag in t'}
              %a{:'ng-click' => "select_tag(tag.id)"}= "{{tag.name}}"
  .tags-nav#one-tag{:'ng-show' => 'one_tag'}
    .type
      %h5 {{one_tag.type}}
      .tag
        %a{:'ng-click' => "select_tag(one_tag.id)"}= "{{one_tag.name}}"
    .row.edit-and-destroy
      %a.btn.edit{:'ng-click' => 'edit_tag(one_tag.id)'}= 'Edit Tag'
      %a.btn.destroy{:'ng-click' => 'delete_tag(one_tag.id)', :'ng-confirm-click' => "Are you sure?"}= 'Delete Tag'
    %h3= "Companies"
    .company{:'ng-repeat' => 'company in one_tag.companies'}
      %a{:'ng-click' => "select_company(company.id)"}= "{{company.ticker}}"

app/views/bioinformatica/index.html.haml
.content{:'ng-app' => 'app'}
  = render :partial => 'nav'
  .container#bioinformatica-main{:'ng-controller' => 'bioinformatica_controller'}
    #stuff{:'ng-switch' => 'type'}
      #companies{:'ng-switch-when' => 'company'}
        = render :partial => 'companies'
      #programs{:'ng-switch-when' => 'drug'}
        .container.span3
          = render :partial => 'tags'
        .container.span8
          = render :partial => 'programs'
      #conversations{:'ng-switch-when' => 'snippet'}
        .container.span3
          = render :partial => 'tags'
        .container.span8
          = render :partial => 'snippets'
      #tag{:'ng-switch-when' => 'tag'}
        .container.span3
          = render :partial => 'tags'
        .container.span8
          = render :partial => 'programs'
          = render :partial => 'snippets'